import { useState, useEffect } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { Shield, CheckCircle, AlertTriangle } from 'lucide-react';

const DISCLAIMER_TEXT = `This compatibility analysis is generated by a rule-based system and is intended as a decision support tool only. It does not constitute astrological advice or a guarantee of marital compatibility.

All results use probabilistic language ("tendency toward", "risk of", "alignment suggests") and do not represent certainties. A "High Alignment" result does not mean the marriage will be successful. A "Detected Risk Zone" does not mean the marriage will fail.

Please verify all results with a qualified Jyotish astrologer before making any marriage-related decisions. This platform logs match outcomes to improve future recommendations. No personally identifiable information is shared with third parties.

By continuing, you acknowledge that you have read and understood these limitations.`;

const STORAGE_KEY = 'jatham-disclaimer-acknowledged';

const DisclaimerModal = ({ onAcknowledge }) => {
  const [show, setShow] = useState(false);
  const [checked, setChecked] = useState(false);

  useEffect(() => {
    // Show once per session
    const acknowledged = sessionStorage.getItem(STORAGE_KEY);
    if (!acknowledged) {
      setShow(true);
    } else {
      onAcknowledge();
    }
  }, []);

  const handleContinue = () => {
    if (!checked) return;
    sessionStorage.setItem(STORAGE_KEY, 'true');
    setShow(false);
    onAcknowledge();
  };

  return (
    <AnimatePresence>
      {show && (
        <motion.div 
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          exit={{ opacity: 0 }}
          className="fixed inset-0 z-[999] bg-black/60 backdrop-blur-sm flex items-center justify-center p-4"
        >
          <motion.div
            initial={{ scale: 0.9, y: 20 }}
            animate={{ scale: 1, y: 0 }}
            exit={{ scale: 0.9, y: 20 }}
            className="bg-white w-full max-w-2xl rounded-[2.5rem] shadow-2xl overflow-hidden"
          >
            {/* Header */}
            <div className="bg-jatham-maroon p-6 text-white">
              <div className="flex items-center gap-3">
                <Shield className="w-8 h-8 text-jatham-gold" />
                <div>
                  <h2 className="text-2xl font-serif">Important Notice</h2>
                  <p className="text-white/70 text-sm">Please read carefully before proceeding</p>
                </div>
              </div>
            </div>
            
            {/* Warning Banner */}
            <div className="bg-amber-50 border-b border-amber-100 px-6 py-3 flex items-center gap-3">
              <AlertTriangle className="w-5 h-5 text-amber-600 shrink-0" />
              <p className="text-amber-700 text-sm font-semibold">
                Jatham is a Decision Support Tool — not a replacement for a qualified astrologer.
              </p>
            </div>

            {/* Disclaimer Text */}
            <div className="p-6 max-h-[40vh] overflow-y-auto">
              <div className="space-y-4 text-jatham-text/70 text-sm leading-relaxed font-sans whitespace-pre-line">
                {DISCLAIMER_TEXT}
              </div>
            </div>

            {/* Checkbox + Button */}
            <div className="p-6 border-t border-jatham-gold/10 space-y-4">
              <label className="flex items-start gap-3 cursor-pointer group">
                <div 
                  className={`mt-0.5 w-5 h-5 rounded border-2 flex items-center justify-center shrink-0 transition-all ${checked ? 'bg-jatham-maroon border-jatham-maroon' : 'border-jatham-gold/40 group-hover:border-jatham-maroon/40'}`}
                  onClick={() => setChecked(v => !v)}
                >
                  {checked && <CheckCircle className="w-4 h-4 text-white" />}
                </div>
                <span className="text-jatham-text text-sm leading-relaxed">
                  I have read and understood the above disclaimer. I acknowledge that this tool is for decision support only and will not replace consultation with a qualified Jyotish astrologer.
                </span>
              </label>

              <button 
                onClick={handleContinue}
                disabled={!checked}
                className={`w-full py-4 rounded-2xl font-bold text-lg transition-all ${checked ? 'bg-jatham-maroon text-white hover:bg-jatham-maroon/90 shadow-lg shadow-jatham-maroon/20' : 'bg-jatham-cream text-jatham-maroon/30 cursor-not-allowed'}`}
              >
                I Understand — View Compatibility Results
              </button>
            </div>
          </motion.div>
        </motion.div>
      )}
    </AnimatePresence>
  );
};

export default DisclaimerModal;
